const blogData = [
  {
    id: 1,
    title: "Exploring the Hidden Gems of Iceland",
    description: "Iceland offers more than just the Golden Circle. This journey takes you through the lesser-known landscapes of Iceland, from the majestic waterfalls of the Westfjords to the volcanic plains of the Highlands. Explore the mystical charm of the northern lights, soak in the geothermal hot springs, and experience the serenity of Iceland’s untamed wilderness. This blog will help you plan the perfect off-the-beaten-path itinerary.",
    author: "Bishal Babu Bohara",
    date: "2024-09-15",
    tags: ["Iceland", "Adventure", "Nature"],
    image: "/assets/iceland.jpg",
    featured: true,
  },
  {
    id: 2,
    title: "Top 10 Must-See Landmarks in Tokyo",
    description: "Tokyo is a city where modernity meets tradition. This guide highlights the top 10 landmarks you shouldn't miss, from the historic Senso-ji Temple to the towering Tokyo Skytree. Explore the vibrant streets of Shibuya, discover the peace of Meiji Shrine, and witness the city's dynamic culture. Whether you're into fashion, food, or history, Tokyo offers something for everyone.",
    author: "Bishal Babu Bohara",
    date: "2024-09-10",
    tags: ["Tokyo", "Landmarks", "Culture"],
    image: "/assets/shibuya-1.jpg",
    featured: false,
  },
  {
    id: 3,
    title: "A Foodie’s Guide to Street Food in Bangkok",
    description: "Bangkok is a paradise for food lovers, especially those who crave authentic street food. From the mouthwatering Pad Thai to the savory Som Tum, this blog explores the best street food stalls across the city. Dive into the bustling markets, where the aroma of grilled meats and fresh herbs fills the air. We'll guide you to hidden gems where locals eat, ensuring you experience the true flavor of Thailand.",
    author: "Bishal Babu Bohara",
    date: "2024-08-30",
    tags: ["Bangkok", "Food", "Culture"],
    image: "/assets/bangkok.jpg",
    featured: false,
  },
  {
    id: 4,
    title: "Hiking Through the Andes: A Journey of a Lifetime",
    description: "Embark on an unforgettable trek through the Andes, where ancient Incan paths lead you through breathtaking landscapes. This blog takes you through some of the most scenic hiking routes in Peru, Bolivia, and Chile. Whether you're hiking the legendary Inca Trail or exploring the rugged beauty of Patagonia, this guide provides tips on preparation, the best seasons to hike, and how to connect with local culture along the way.",
    author: "Bishal Babu Bohara",
    date: "2024-09-05",
    tags: ["Hiking", "Andes", "Adventure"],
    image: "/assets/andes.jpg",
    featured: true,
  },
  {
    id: 5,
    title: "How to Travel on a Budget in Europe",
    description: "Traveling through Europe doesn't have to drain your wallet. In this guide, you'll learn how to travel across the continent on a budget without sacrificing comfort or experience. From finding affordable accommodations and local eats to discovering free attractions in major cities like Paris, Rome, and Prague, we cover all the tips to stretch your euros. With smart planning, Europe’s beauty is within reach.",
    author: "Bishal Babu Bohara",
    date: "2024-07-20",
    tags: ["Europe", "Budget Travel", "Tips"],
    image: "/assets/europe.jpg",
    featured: true,
  },
  {
    id: 6,
    title: "A Safari Adventure in the Serengeti",
    description: "The Serengeti is home to one of the most diverse and spectacular ecosystems in the world. This blog details a safari adventure that allows you to witness the 'Big Five' in their natural habitat. Get up close with lions, elephants, and giraffes, and witness the Great Migration, where millions of wildebeests and zebras travel across the plains. Learn how to prepare for a safari, what to expect, and how to make the most of your time in this extraordinary environment.",
    author: "Bishal Babu Bohara",
    date: "2024-06-15",
    tags: ["Safari", "Serengeti", "Wildlife"],
    image: "/assets/serengeti.jpg",
    featured: true,
  },
  {
    id: 7,
    title: "The Best Beaches in the Caribbean",
    description: "The Caribbean is home to some of the world’s most beautiful beaches, each with its own unique charm. This blog highlights the best beaches for swimming, sunbathing, and water sports. Whether you're looking for quiet, secluded spots or bustling shores with vibrant nightlife, we’ll guide you through the islands, from Jamaica to the Bahamas, with tips on how to enjoy each location to the fullest.",
    author: "Bishal Babu Bohara",
    date: "2024-08-10",
    tags: ["Beaches", "Caribbean", "Relaxation"],
    image: "/assets/carribean.jpg",
    featured: false,
  },
  {
    id: 8,
    title: "Discovering Ancient Temples in Cambodia",
    description: "Cambodia’s ancient temples are a window into the past. This blog takes you on a journey to discover the architectural wonders of Angkor Wat, Bayon Temple, and Ta Prohm. Marvel at the intricate carvings and learn the history behind these spiritual sites. Along the way, immerse yourself in Cambodia’s rich culture and traditions, experiencing the warmth and hospitality of its people.",
    author: "Bishal Babu Bohara",
    date: "2024-09-02",
    tags: ["Cambodia", "History", "Temples"],
    image: "/assets/cambodia.jpg",
    featured: false,
  },
  {
    id: 9,
    title: "A Road Trip Through the Australian Outback",
    description: "An epic journey awaits in the Australian Outback. This road trip takes you through vast deserts, iconic rock formations like Uluru, and unique wildlife encounters. With endless horizons and rugged landscapes, the Outback offers a true escape from the city. We’ll provide tips on planning your route, camping under the stars, and experiencing the heart of Australia’s wilderness.",
    author: "Bishal Babu Bohara",
    date: "2024-09-18",
    tags: ["Australia", "Road Trip", "Adventure"],
    image: "/assets/australia.jpg",
    featured: false,
  },
  {
    id: 10,
    title: "Cultural Wonders of Morocco: From Souks to Sahara",
    description: "Morocco is a land of contrasts, where vibrant souks and ancient medinas meet the endless expanse of the Sahara Desert. This blog will take you on a cultural journey through the bustling streets of Marrakech, the blue city of Chefchaouen, and the serene sands of the Sahara. Learn about Moroccan traditions, cuisine, and how to navigate the country like a local.",
    author: "Bishal Babu Bohara",
    date: "2024-08-25",
    tags: ["Morocco", "Culture", "Desert"],
    image: "/assets/morocco.jpg",
    featured: true,
  },
  {
    id: 11,
    title: "Exploring the Fjords of Norway: Nature's Majesty",
    description: "Norway is home to some of the most breathtaking fjords in the world. This blog will guide you through the stunning landscapes of Geirangerfjord, Nærøyfjord, and the Lofoten Islands. Discover the best hiking trails, boat tours, and scenic drives to fully immerse yourself in Norway’s natural beauty.",
    author: "Bishal Babu Bohara",
    date: "2024-09-05",
    tags: ["Norway", "Fjords", "Nature"],
    image: "/assets/norway.jpg",
    featured: true
},
{
    id: 12,
    title: "Tokyo by Night: Neon Dreams and Hidden Gems",
    description: "Tokyo transforms into a neon wonderland at night, offering a unique blend of modernity and tradition. Explore the city's vibrant nightlife, from the bustling streets of Shibuya to the quiet temples hidden in the urban jungle. Learn how to navigate the city’s late-night food scene and discover lesser-known gems.",
    author: "Bishal Babu Bohara",
    date: "2024-09-12",
    tags: ["Tokyo", "Nightlife", "City"],
    image: "/assets/tokyo.jpg",
    featured: false
},
{
    id: 13,
    title: "A Journey Through the Heart of Tuscany: Wine, Art, and History",
    description: "Tuscany, with its rolling hills, vineyards, and medieval towns, is a paradise for travelers seeking art, history, and incredible cuisine. This blog takes you through the heart of Italy’s most iconic region, exploring the art of Florence, the vineyards of Chianti, and the hidden gems of the countryside.",
    author: "Bishal Babu Bohara",
    date: "2024-08-30",
    tags: ["Tuscany", "Wine", "History"],
    image: "/assets/tuscany.jpg",
    featured: true
},
{
    id: 14,
    title: "Patagonia: The Last Untamed Wilderness",
    description: "Patagonia is one of the most remote and awe-inspiring regions in the world. This blog takes you through the rugged landscapes of Argentina and Chile, where glaciers meet jagged mountain peaks and wildlife roams freely. Learn the best ways to explore Torres del Paine and Fitz Roy, and immerse yourself in the raw beauty of Patagonia.",
    author: "Bishal Babu Bohara",
    date: "2024-09-20",
    tags: ["Patagonia", "Wilderness", "Adventure"],
    image: "/assets/patagonia.jpg",
    featured: false
},
{
    id: 15,
    title: "Discovering the Temples of Angkor: Cambodia's Ancient Marvels",
    description: "Cambodia's Angkor Wat is a must-visit for any traveler interested in history and architecture. This blog will guide you through the ancient temples of Angkor, from the iconic Angkor Wat to the hidden treasures of Ta Prohm and Bayon. Learn the best times to visit and how to appreciate the intricate carvings and history behind these wonders.",
    author: "Bishal Babu Bohara",
    date: "2024-08-18",
    tags: ["Cambodia", "Temples", "History"],
    image: "/assets/ankorwat.jpg",
    featured: true
}

  // Add more blog entries here
];

export default blogData;
